/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatCard: typeof import('./components/ChatCard.vue')['default']
    HealthMonitoring: typeof import('./components/HealthMonitoring.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ProgressCard: typeof import('./components/ProgressCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/TheSidebar.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    VaccinationSchedule: typeof import('./components/VaccinationSchedule.vue')['default']
  }
}
