/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/LoginForm': RouteRecordInfo<'/auth/LoginForm', '/auth/LoginForm', Record<never, never>, Record<never, never>>,
    '/auth/RecoverPasswordForm': RouteRecordInfo<'/auth/RecoverPasswordForm', '/auth/RecoverPasswordForm', Record<never, never>, Record<never, never>>,
    '/auth/RegisterForm': RouteRecordInfo<'/auth/RegisterForm', '/auth/RegisterForm', Record<never, never>, Record<never, never>>,
    '/DashboardPage': RouteRecordInfo<'/DashboardPage', '/DashboardPage', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth/LoginForm.vue': {
      routes: '/auth/LoginForm'
      views: never
    }
    'src/pages/auth/RecoverPasswordForm.vue': {
      routes: '/auth/RecoverPasswordForm'
      views: never
    }
    'src/pages/auth/RegisterForm.vue': {
      routes: '/auth/RegisterForm'
      views: never
    }
    'src/pages/DashboardPage.vue': {
      routes: '/DashboardPage'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
